### ISSUE TITLE
make error using libedit-dev 3.1-20130712-2

### ISSUE THREAD

**Issue by emig** [yrp604/rappel#13]
Thanks for this, I love REPLs!

I encountered a 'make' error when using an old version of **libedit-dev (3.1-20130712)** on my Ubuntu Trusty box.

I am new to C, my newb question is:  **how are library version requirements specified**?.

Details: 
the commit requiring a newer version is c8aeae9328dd59adb0bb6f43fa0edde3ecbff941 ; it uses an identifier (H_SAVE_FP) that is not present in libedit-dev 3.1-20130712-2 (latest on Ubuntu Trusty). 

make fails on trusty (libedit-dev 3.1-20130712-2): https://travis-ci.org/emig/rappel/builds/544237957#L481-L488 
make builds on xenial (3.1-20150325-1ubuntu2): https://travis-ci.org/emig/rappel/builds/544237957#L481-L488 

I wasn't able to find the precise version of libedit-dev that starts working with the code. The closer I got is the change on the libedit history.c file that brings the new identifier http://cvsweb.netbsd.org/bsdweb.cgi/src/lib/libedit/history.c.diff?r1=1.46&r2=1.47&sortby=date&f=h 
since the header file wasn't on this repository, I assume it is generated from it.

**Comment by yrp604** [comment]
No problem, I’m glad you’ve found it useful, and good work tracking down the history to find where this was introduced.  

In C, library versions are generally specified via autoconf script, which will set up some defines to wall off or enable features. I’d really rather not introduce this, especially for an 8 year old code change in a 5 year old end of life’d distro. However, this reluctance is mostly due to laziness in my part — if there’s a good reason to support older distros I’m game to reconsider.

**Comment by emig** [comment]
Fair enough, thanks for feedback.
