### ISSUE TITLE
assembling illegal insrtuctins may delete /dev/stdout file

### ISSUE THREAD

**Issue by thatreguy** [yrp604/rappel#14]
Observed that assembling instructions like `mov rax, rbbx` remove the /dev/stdout file when running as root

**Comment by yrp604** [comment]
I'm having trouble reproducing this:

```
root@daedra:/home/x/src/rappel# bin/rappel
rax: 0x0000000000000000 rbx: 0x0000000000000000 rcx: 0x0000000000000000 rdx: 0x0000000000000000
rsi: 0x0000000000000000 rdi: 0x0000000000000000 r8 : 0x0000000000000000 r9 : 0x0000000000000000
r10: 0x0000000000000000 r11: 0x0000000000000000 r12: 0x0000000000000000 r13: 0x0000000000000000
r14: 0x0000000000000000 r15: 0x0000000000000000
rip: 0x0000000000400001 rsp: 0x00007ffdc9148b20 rbp: 0x0000000000000000
flags: 0x0000000000000202 [cf:0, zf:0, of:0, sf:0, pf:0, af:0, df:0]
> mov rax, rbbx
nasm exited 1.
execlp: No such file or directory
'' assembled to 0 length bytecode
> ^D
root@daedra:/home/x/src/rappel# ls -l /dev |grep stdout
lrwxrwxrwx 1 root root          15 Jun 23 15:25 stdout -> /proc/self/fd/1
```

I also don't actually unlink anything in the x86 code, meaning this would be nasm trying to clean up after itself. Could you try changing `/dev/stdout` to `/proc/self/fd/1` in the amd64 nasm invocation and see if that fixes your issue? Even if that file is removed, it shouldn't matter because that proc entry should die with the process...

**Comment by yrp604** [comment]
Fixed, thanks for the bug report!
